### ISSUE TITLE
Error CS0122 - DXCollectionViewBase.g.cs

### ISSUE THREAD

**Issue by dixboss** [adospace/mauireactor-integration#2]
Hello,

Could you please help me with there errors? I'm getting there errors while trying to integrate DXCollectionView ont NET 8.

DXCollectionViewBase.g.cs(60,105): Error CS0122 : 'DXCollectionViewBase.FooterProperty' is inaccessible due to its protection level
DXCollectionViewBase.g.cs(61,105): Error CS0122 : 'DXCollectionViewBase.HeaderProperty' is inaccessible due to its protection level
DXCollectionViewBase.g.cs(62,105): Error CS0122 : 'DXCollectionViewBase.IsRefreshingProperty' is inaccessible due to its protection level
DXCollectionViewBase.g.cs(63,105): Error CS0122 : 'DXCollectionViewBase.ScrollItemCountProperty' is inaccessible due to its protection level
DXCollectionViewBase.g.cs(64,105): Error CS0122 : 'DXCollectionViewBase.ShowFooterProperty' is inaccessible due to its protection level
DXCollectionViewBase.g.cs(65,105): Error CS0122 : 'DXCollectionViewBase.ShowHeaderProperty' is inaccessible due to its protection level

**Comment by adospace** [comment]
Hi, 
I've fixed the issue in the latest sample just published:
https://github.com/adospace/mauireactor-integration/blob/main/DevExpress/DevExpressIntApp/Pages/MainPage.cs

Please take a look at sample for the DxCollectionView implementation with latest MauiReactor version.
