### ISSUE TITLE
DevExpress.Maui.Core.DXButton  <PackageReference Include="DevExpress.Maui.Core" Version="24.1.7" /> There is a problem with use, it seems that the generated proxy file has called an inaccessible field and cannot be used

### ISSUE THREAD

**Issue by aidenwlf** [adospace/mauireactor-integration#4]
[Scaffold(typeof(DevExpress.Maui.Core.DXButton))]
public partial class DXButton { }

[Scaffold(typeof(DevExpress.Maui.Core.DXButtonBase))]
public abstract class DXButtonBase { }

[Scaffold(typeof(DevExpress.Maui.Core.DXContentPresenter))]
public partial class DXContentPresenter { }

[Scaffold(typeof(DevExpress.Maui.Core.DXContentPresenterBase))]
public abstract class DXContentPresenterBase { }

[Scaffold(typeof(DevExpress.Maui.Core.DXBorder))]
public partial class DXBorder { }

[Scaffold(typeof(DevExpress.Maui.Core.DXViewBase))]
public abstract class DXViewBase { }

[Scaffold(typeof(DevExpress.Maui.Core.Internal.DXViewBaseCore))]
public abstract class DXViewBaseCore { }

[Scaffold(typeof(DevExpress.Maui.Core.Internal.DXViewElement))]
public abstract class DXViewElement { }

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误(活动)	CS0122	“DXButtonBase.AllowUncheckInGroupProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	200		
警告(活动)	CS0108	“IDXButtonBase.TapReleasedActionWithArgs”隐藏继承的成员“IDXViewBaseCore.TapReleasedActionWithArgs”。如果是有意隐藏，请使用关键字 new。	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	98		
错误(活动)	CS0122	“DXButtonBase.CheckedBackgroundColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	202		
错误(活动)	CS0122	“DXButtonBase.CheckedBorderColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	203		
错误(活动)	CS0122	“DXButtonBase.CheckedDisabledBackgroundColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	204		
错误(活动)	CS0122	“DXButtonBase.CheckedDisabledBorderColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	205		
错误(活动)	CS0122	“DXButtonBase.CheckedDisabledIconColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	206		
错误(活动)	CS0122	“DXButtonBase.CheckedDisabledTextColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	207		
错误(活动)	CS0122	“DXButtonBase.CheckedIconColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	208		
错误(活动)	CS0122	“DXButtonBase.CheckedPressedBackgroundColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	209		
错误(活动)	CS0122	“DXButtonBase.CheckedPressedBorderColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	210		
错误(活动)	CS0122	“DXButtonBase.CheckedPressedIconColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	211		
错误(活动)	CS0122	“DXButtonBase.CheckedPressedTextColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	212		
错误(活动)	CS0122	“DXButtonBase.CheckedTextColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	213		
错误(活动)	CS0122	“DXButtonBase.GroupNameProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	218		
错误(活动)	CS0122	“DXButtonBase.IsCheckedProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	219		
错误(活动)	CS0122	“DXButtonBase.CheckedChanged”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	255		
错误(活动)	CS0122	“DXButtonBase.CheckedChanging”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	260		
错误(活动)	CS0122	“DXButtonBase.CheckedChanged”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	333		
错误(活动)	CS0122	“DXButtonBase.CheckedChanging”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	334		
错误(活动)	CS0122	“DXViewBaseCore.BorderColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	147		
错误(活动)	CS0122	“DXViewBaseCore.BorderThicknessProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	148		
错误(活动)	CS0122	“DXViewBaseCore.CornerRadiusProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	149		
错误(活动)	CS0122	“DXViewBaseCore.HorizontalContentAlignmentProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	150		
错误(活动)	CS0122	“DXViewBaseCore.IsClippedToBoundsProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	151		
错误(活动)	CS0122	“DXViewBaseCore.PaddingProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	152		
错误(活动)	CS0122	“DXViewBaseCore.RippleColorProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	153		
错误(活动)	CS0122	“DXViewBaseCore.VerticalContentAlignmentProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	154		
错误(活动)	CS0122	“DXViewBaseCore.DoubleTap”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	181		
错误(活动)	CS0122	“DXViewBaseCore.LongTap”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	186		
错误(活动)	CS0122	“DXViewBaseCore.Measured”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	191		
错误(活动)	CS0122	“DXViewBaseCore.Pan”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	196		
错误(活动)	CS0122	“DXViewBaseCore.Swipe”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	201		
错误(活动)	CS0122	“DXViewBaseCore.Tap”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	206		
错误(活动)	CS0122	“DXViewBaseCore.TapPressed”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	211		
错误(活动)	CS0122	“DXViewBaseCore.TapReleased”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	216		
错误(活动)	CS0122	“DXViewBaseCore.DoubleTap”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	283		
错误(活动)	CS0122	“DXViewBaseCore.LongTap”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	284		
错误(活动)	CS0122	“DXViewBaseCore.Measured”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	285		
错误(活动)	CS0122	“DXViewBaseCore.Pan”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	286		
错误(活动)	CS0122	“DXViewBaseCore.Swipe”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	287		
错误(活动)	CS0122	“DXViewBaseCore.Tap”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	288		
错误(活动)	CS0122	“DXViewBaseCore.TapPressed”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	289		
错误(活动)	CS0122	“DXViewBaseCore.TapReleased”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	290		
错误(活动)	CS0122	“DXViewBaseCore.BorderThicknessProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	363		
错误(活动)	CS0122	“DXViewBaseCore.BorderThicknessProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	378		
错误(活动)	CS0122	“DXViewBaseCore.BorderThicknessProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	386		
错误(活动)	CS0122	“DXViewBaseCore.BorderThicknessProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	394		
错误(活动)	CS0122	“DXViewBaseCore.CornerRadiusProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	402		
错误(活动)	CS0122	“DXViewBaseCore.CornerRadiusProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	417		
错误(活动)	CS0122	“DXViewBaseCore.CornerRadiusProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	425		
错误(活动)	CS0122	“DXViewBaseCore.PaddingProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	475		
错误(活动)	CS0122	“DXViewBaseCore.PaddingProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	490		
错误(活动)	CS0122	“DXViewBaseCore.PaddingProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	498		
错误(活动)	CS0122	“DXViewBaseCore.PaddingProperty”不可访问，因为它具有一定的保护级别	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXViewBaseCore.g.cs	506		
错误(活动)	CS1503	参数 1: 无法从“KMCLReactor.Pages.DXButton”转换为“MauiReactor.VisualNode”	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\Pages\MainPage.cs	15		
警告(活动)	CS0108	“IDXButtonBase.TapAction”隐藏继承的成员“IDXViewBaseCore.TapAction”。如果是有意隐藏，请使用关键字 new。	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	88		
警告(活动)	CS0108	“IDXButtonBase.TapActionWithArgs”隐藏继承的成员“IDXViewBaseCore.TapActionWithArgs”。如果是有意隐藏，请使用关键字 new。	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	90		
警告(活动)	CS0108	“IDXButtonBase.TapPressedAction”隐藏继承的成员“IDXViewBaseCore.TapPressedAction”。如果是有意隐藏，请使用关键字 new。	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	92		
警告(活动)	CS0108	“IDXButtonBase.TapPressedActionWithArgs”隐藏继承的成员“IDXViewBaseCore.TapPressedActionWithArgs”。如果是有意隐藏，请使用关键字 new。	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	94		
警告(活动)	CS0108	“IDXButtonBase.TapReleasedAction”隐藏继承的成员“IDXViewBaseCore.TapReleasedAction”。如果是有意隐藏，请使用关键字 new。	KMCLReactor (net8.0-android)	C:\Users\84018\source\repos\KMCLReactor\obj\Debug\net8.0-android\MauiReactor.ScaffoldGenerator\MauiReactor.ScaffoldGenerator.ScaffoldSourceGenerator\KMCLReactor.Pages.DXButtonBase.g.cs	96

**Comment by adospace** [comment]
sorry for the delay, next time please describe your issue better, it will help me in prioritize tasks, thanks,

Fixed in MauiReactor 2.0.59
I've also updated the project https://github.com/adospace/mauireactor-integration/tree/main/DevExpress

BTW DevExpress controls are pretty complex, you'll probably encounter other problems in integrating them, in case just let me know
