### ISSUE TITLE
Syncfusion SfCarouselView problem

### ISSUE THREAD

**Issue by powerdude** [adospace/mauireactor-integration#5]
I've set up scaffolding for the `SfCarouselView` control, but unfortunately it fails because the `ItemSource` property of the base control is an `IEnumerable<object>` instead of just `IEnumerable`.  Would you consider changing the generated interface for `ItemsSource` to be `IEnumerable<object>` since it inherits from `IEnumerable`?

```csharp
[Scaffold(typeof(Syncfusion.Maui.Carousel.SfCarousel), implementItemTemplate:true)]
public partial class SfCarousel { }
```

**Comment by adospace** [comment]
I can't modify the type as it's used in the standard ItemsView control, anyway, I've fixed it in the generated code casting to the original ItemsSouce property type, please get a look at the implementation here:
https://github.com/adospace/mauireactor-integration/blob/main/Syncfusion/SfIntApp/Pages/CarouselPage.cs

Fixed using MauiReactor 2.0.58
